#!/bin/bash

source_root=/home/dean
backup_root=/media/BACKUPS/VMs
directory_list="bin Music Pictures public_html Videos"

#rsync -av --modify-window=5 --delete-excluded \
   #--exclude-from=/home/dean/conf/exclude_backup\
   #/home/dean/ /media/BACKUPS/dean_backup \
   #> /home/dean/log/nightly_backup.log \
   #2> /home/dean/log/nightly_backup.error

rsync -av --modify-window=5 "/home/dean/VirtualBox VMs" \
   "/media/BACKUPS/VirtualBox VMs"

