#!/bin/bash

while read line; do
   grep "$line" ~/conf/Pictures_list > /dev/null 2>&1
   status=$?

   if [ $status -ne 0 ]; then
      echo "$line not found"
   fi
done < /home/dean/conf/Pictures.save_list2
