#!/bin/bash

ls -1 /home/dean/Music > /tmp/artists


while read artist; do
   echo "----------------------------------------------------"
   echo ${artist}
   echo "----------------------------------------------------"

   cd "/home/dean/Music/${artist}"

   ls -1 . > /tmp/albums
  
   while read album; do
      cd "/home/dean/Music/${artist}/${album}"
      tmp_artist=`find . -name "01*" -exec id3v2 -l {} \; | egrep 'TPE' \
         | awk -F':' '{print $2}'`

      echo "${tmp_artist}:  ${album}"
   done < /tmp/albums
  
   echo ""
done < /tmp/artists
