#!/bin/bash

mencoder dvd://6 -dvd-device /dev/dvd  -alang English    \
   -info srcform="DVD ripped by acidrip.sf.net" -oac copy   \
   -ovc x264 -vf pp=de,crop=0:0:0:0,scale=720:-2    \
   -x264encopts qp=26:pass=1 \
    -o "/home/dean/Swan_Lake.avi"
