#!/bin/bash 

base=/home/dean/Pictures

while read line; do 

   year=`echo $line | cut -c1-4`    
   monthno=`echo $line | cut -c5-6`    
   dayno=`echo $line | cut -c7-8`    

   case "$monthno" in 
      01)
         month="January";
      ;;
      02)
         month="February";
      ;;
      03)
         month="March";
      ;;
      04)
         month="April";
      ;;
      05)
         month="May";
      ;;
      06)
         month="June";
      ;;
      07)
         month="July";
      ;;
      08)
         month="August";
      ;;
      09)
         month="September";
      ;;
      10)
         month="October";
      ;;
      11)
         month="November";
      ;;
      12)
         month="December";
      ;;
   esac

   
   title="${month} ${dayno}, ${year}"

   picpath="${base}/${year}/${monthno}/${dayno}"

   #Check for presence of Web Album
   album_exist=`google picasa list --title "${title}" | wc -l`

   #if [ $album_exist -eq 0 ]; then
      #echo "${title} exists"
      google picasa create --title "${title}" 
      #echo "google picasa create --title \"${title}\" "
   #fi

   
   google picasa post --title "${month} ${dayno}, ${year}" ${picpath}/${line}
   #echo "google picasa post --title \"${month} ${dayno}, ${year}\" ${picpath}/${line}"
   #google picasa post --title "${month} ${dayno}, ${year}" ${line}/*.jpg
    
   #echo "google picasa create --title \"${month} ${dayno}, ${year}\" "
   #echo "google picasa post --title \"${month} ${dayno}, ${year}\" ${line}/*.JPG"
   #echo "google picasa post --title \"${month} ${dayno}, ${year}\" ${line}/*.jpg"
 
done < ~/conf/missing_jpegs


