#!/bin/bash 

rsync -avz --delete /home/dean/media/Videos pi@192.168.0.22:/media/extstorage/
rsync -avz --delete /home/dean/media/Music pi@192.168.0.22:/media/extstorage/
rsync -avz --delete /home/dean/media/Pictures pi@192.168.0.22:/media/extstorage/

#ssh pi@rasbpi sudo /etc/init.d/minidlna force-reload
