#!/bin/bash

#rsync -avz /media/Elements/Videos/ dean@diskstation:/volume1/video
#rsync -avz --delete /home/dean/Videos/ dean@diskstation:/volume1/video
rsync -avz --delete /home/dean/Videos/ /media/Elements/Videos/
ssh dean@diskstation -n "synoindex -R video"
